### ISSUE TITLE
На макбуке (13" Retina) показывает мобильную версию.

### ISSUE THREAD

**Issue by 2bj** [coderiver/parampampamrepo#1]
![Alt text](https://monosnap.com/file/YIXqI2WVGKbg1C8zIzC4VYxC6jl813.png)

**Comment by whats0n** [comment]
Мы этот момент уже обсуждали ранее, в дизайне не взяли во внимание размеры логотипа, поиска, кнопок профайла когда рисовали адаптив, из-за чего он не подходит, решили сделать переход в мобильное состояние раньше :)
