### ISSUE TITLE
js-select

### ISSUE THREAD

**Issue by 2bj** [coderiver/parampampamrepo#11]
Как в js-select (который очень странный) сделать элементарный selected: `<option value="" selected></option>`?

``` html
<div class="special-form__gender">
    <div class="special-form__label">Пол</div>
    <div class="select select_white js-select">
        <div class="select__text js-select-text"></div>
        <i class="fa fa-angle-down"></i>
        <ul class="select__list js-select-list">
            <li data-val="любой">любой</li>
            <li data-val="женский">женский</li>
            <li data-val="мужской">мужской</li>
        </ul>
        <select>
            <option value="любой">любой</option>
            <option value="женский">женский</option>
            <option value="мужской">мужской</option>
        </select>
    </div>
</div>
```

Мне кажется, это очень не правильное решение. Как насчет взять готовую либу и откастомайзить? Предлагаю ту, кот я использую в проекте (в старой версии) http://marcj.github.io/jquery-selectBox/

Это очень срочный тикет.

Спасибо!

**Comment by whats0n** [comment]
Обновил, в там на страничке dislife-text-special-puzzles-user-profile.html - сделал только один, расплодить думаю сами сможете же? :)

**Comment by 2bj** [comment]
Отлично! Спасибо большое!
