### ISSUE TITLE
border-radius

### ISSUE THREAD

**Issue by 2bj** [coderiver/parampampamrepo#3]
![Alt text](https://monosnap.com/file/AKbOv8IyhYMFfheMF3FxbGmOhMNZvc.png)

Вот это же можно сделать на CSS? Чтобы я загружал квадратные фотки, а ты CSS'ом рисуешь красивую форму

**Comment by 2bj** [comment]
`border-radius: 50% 50% 0;`

**Comment by whats0n** [comment]
done
