### ISSUE TITLE
<span> tag

### ISSUE THREAD

**Issue by 2bj** [coderiver/parampampamrepo#5]
![Alt text](https://monosnap.com/file/ei2VkFcwmMpaX2GojstVbNjmocHKm5.png)

А для чего этот лишний тег SPAN?
Надо убрать.

**Comment by 2bj** [comment]
Текст тут заполняется через админку, и никакой редактор не будет каждый раз вставлять лишний тег.
Если еще где-то в контенте есть такие хаки - уберите.
Спасибо!

**Comment by whats0n** [comment]
done! :) проверил на текстовых стр. такого не видел больше)
