### ISSUE TITLE
figure center

### ISSUE THREAD

**Issue by 2bj** [coderiver/parampampamrepo#6]
![Alt text](https://monosnap.com/file/CPoMOH1H36eLo7IteHCsRyD7tYICBI.png)

если картинка портретная, то нужно отцентровать 
спасибо!

**Comment by 2bj** [comment]
к слайдеру тоже относится

![Alt text](https://monosnap.com/file/SMAkuce1o8C0CzvD0n4FLJL4lusZb2.png)

**Comment by whats0n** [comment]
done
