### ISSUE TITLE
js-slider-images captions

### ISSUE THREAD

**Issue by 2bj** [coderiver/parampampamrepo#7]
![Alt text](https://monosnap.com/file/KpMTS0bVQUDosqjQI2ykX1QEjDYfdw.png)

у каждой картинки - свой кэпшн,  нужно стили подогнать под это
спасибо

**Comment by 2bj** [comment]
я попробовал, но что-то не получается :(

![Alt text](https://monosnap.com/file/EVLcVEmpgs85R0HYUDb9FbeHVyYD3y.png)

**Comment by whats0n** [comment]
done
